from enemy.enemy_type import EnemyType

GAME_ACTIVE = 0
GAME_WIN = 1
GAME_LOSS_COLLISION = 2
GAME_LOSS_SPEED = 3
GAME_ROUND_INTERIM = 4

GAME_LOSS_STATES = (GAME_LOSS_COLLISION, GAME_LOSS_SPEED)

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)

# CONFIG
WIDTH = 800
HEIGHT = 600
SPAWN_AREA_BORDER_BUFFER = 100
ACTIVE_WIDTH = WIDTH
ACTIVE_HEIGHT = HEIGHT
DESPAWN_BUFFER = 150

DEBUG = False

SHIP_IMAGE = "ship"
SHIP_ACC = 0.1
SHIP_BRAKE_DECELERATION = SHIP_ACC / 10
SHIP_MAX_SPEED = 100
SHIP_RAM_SPEED = 25
SHIP_SHIELD_ACTIVE_TIME = 5
SHIP_SHIELD_REQ_CHARGE = 25
SHIP_BRAKE_DECELERATION = 50
SHIP_DECELERATION_MULTIPLIER = 0.99

ENEMY_DEFAULT_SPEED = 1
ENEMY_MIN_SPEED = 0.1
ENEMY_MAX_SPEED = 2

BULLET_TIME_TO_LIVE = 2

BACKGROUND = "background"
UI_INFO_FONT_SIZE = 30

ROUND_1_ASTEROIDS = 1
ROUND_INTERIM_LENGTH = 5


